name: Update Events

on:
  schedule:
    - cron: "*/10 * * * *"   # 每10分钟执行一次
  workflow_dispatch:

jobs:
  update-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download events.json file
        run: |

      - name: Configure Git for commit
        run: |
          git config user.name "Event Synchronization Bot"

      - name: Commit and push changes
        run: |
          git add data/events.json
          if ! git diff-index --quiet HEAD; then
            git commit -m "自动更新 events.json 文件"
            git push
          else
            echo "No changes detected."
          fi